### ISSUE TITLE
Not working [fixed]

### ISSUE THREAD

**Issue by mrbeandev** [N74NK/BTC#1]
The script is stopping in middle after gaining some rewards it is showing 
Sending command and it is stopping right there..please help
See the attachment
![Screenshot_2019-05-11-06-11-23-630_com termux](https://user-images.githubusercontent.com/34623886/57562805-aec50b00-73b3-11e9-9810-6c65f6a6523d.png)

**Comment by Yutix** [comment]
Skip ads manual or views ads manual to bypass stuck
